export const moviesList = [
    {
      id: 1,
      title: "Avatar: The Way of Water",
      cert: "UA",
      langs: "English, Hindi, Tamil, Telugu",
      image: "https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_FMjpg_UX1000_.jpg",
      cover: "https://images.unsplash.com/photo-1542204165-65bf26472b9b?auto=format&fit=crop&q=80&w=2000",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Avatar_The_Way_of_Water_logo.svg/1024px-Avatar_The_Way_of_Water_logo.svg.png",
      rating: "9.2/10",
      votes: "120K+ Votes",
      ratingColor: "text-fuchsia-400",
      tags: ['Thriller/Mystery', 'Action', 'Adventure', 'Fantasy'],
      imdb: "7.6",
      pg: "13 (18+)",
      duration: "3h 12m",
      description: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
      director: "James Cameron",
      writers: "Rick Jaffa • Amanda Silver",
      stars: "Sam Worthington • Zoe Saldaña • Sigourney Weaver"
    },
    {
      id: 2,
      title: "Dune: Part Two",
      cert: "UA16+",
      langs: "English, Hindi",
      image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&q=80",
      cover: "https://images.unsplash.com/photo-1542204165-65bf26472b9b?auto=format&fit=crop&q=80&w=2000",
      logo: "", 
      rating: "9.5/10",
      votes: "85K+ Votes",
      ratingColor: "text-amber-400",
      tags: ['Sci-Fi', 'Adventure', 'Drama'],
      imdb: "8.8",
      pg: "16+",
      duration: "2h 46m",
      description: "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe.",
      director: "Denis Villeneuve",
      writers: "Denis Villeneuve • Jon Spaihts",
      stars: "Timothée Chalamet • Zendaya • Rebecca Ferguson"
    },
    {
      id: 3,
      title: "Oppenheimer",
      cert: "A",
      langs: "English, Hindi",
      image: "https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_FMjpg_UX1000_.jpg",
      cover: "https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?auto=format&fit=crop&q=80&w=2000",
      logo: "",
      rating: "8.9/10",
      votes: "250K+ Votes",
      ratingColor: "text-fuchsia-400",
      tags: ['Biography', 'Drama', 'History'],
      imdb: "8.3",
      pg: "R",
      duration: "3h 0m",
      description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
      director: "Christopher Nolan",
      writers: "Christopher Nolan",
      stars: "Cillian Murphy • Emily Blunt • Matt Damon"
    },
    {
      id: 4,
      title: "Interstellar",
      cert: "U",
      langs: "English",
      image: "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg",
      cover: "https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?auto=format&fit=crop&q=80&w=2000",
      logo: "",
      rating: "93%",
      votes: "1.2M+ Likes",
      ratingColor: "text-emerald-400",
      tags: ['Sci-Fi', 'Adventure', 'Drama'],
      imdb: "8.7",
      pg: "13",
      duration: "2h 49m",
      description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
      director: "Christopher Nolan",
      writers: "Jonathan Nolan • Christopher Nolan",
      stars: "Matthew McConaughey • Anne Hathaway • Jessica Chastain"
    },
    {
      id: 5,
      title: "Suzume",
      cert: "U",
      langs: "Japanese, Hindi, English",
      image: "https://images.unsplash.com/photo-1578301978018-3005759f48f7?w=800&q=80",
      cover: "https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?auto=format&fit=crop&q=80&w=2000",
      logo: "",
      rating: "9.1/10",
      votes: "45K+ Votes",
      ratingColor: "text-amber-400",
      tags: ['Animation', 'Action', 'Adventure'],
      imdb: "7.7",
      pg: "PG",
      duration: "2h 2m",
      description: "A modern action adventure road story where a 17-year-old girl named Suzume helps a mysterious young man close doors from the other side that are releasing disasters all over in Japan.",
      director: "Makoto Shinkai",
      writers: "Makoto Shinkai",
      stars: "Nanoka Hara • Hokuto Matsumura • Eri Fukatsu"
    },
    {
      id: 6,
      title: "The Batman",
      cert: "UA16+",
      langs: "English, Hindi, Tamil",
      image: "https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_FMjpg_UX1000_.jpg",
      cover: "https://images.unsplash.com/photo-1542204165-65bf26472b9b?auto=format&fit=crop&q=80&w=2000",
      logo: "",
      rating: "8.5/10",
      votes: "150K+ Votes",
      ratingColor: "text-fuchsia-400",
      tags: ['Action', 'Crime', 'Drama'],
      imdb: "7.8",
      pg: "13",
      duration: "2h 56m",
      description: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
      director: "Matt Reeves",
      writers: "Matt Reeves • Peter Craig",
      stars: "Robert Pattinson • Zoë Kravitz • Jeffrey Wright"
    },
    {
      id: 7,
      title: "Spider-Man: Across the Spider-Verse",
      cert: "U",
      langs: "English, Hindi",
      image: "https://images.unsplash.com/photo-1608889175123-8ee362201f81?w=800&q=80",
      cover: "https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?auto=format&fit=crop&q=80&w=2000",
      logo: "",
      rating: "95%",
      votes: "800K+ Likes",
      ratingColor: "text-emerald-400",
      tags: ['Animation', 'Action', 'Adventure'],
      imdb: "8.6",
      pg: "PG",
      duration: "2h 20m",
      description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
      director: "Joaquim Dos Santos",
      writers: "Phil Lord • Christopher Miller",
      stars: "Shameik Moore • Hailee Steinfeld • Brian Tyree Henry"
    },
    {
      id: 8,
      title: "John Wick: Chapter 4",
      cert: "A",
      langs: "English, Hindi",
      image: "https://m.media-amazon.com/images/M/MV5BMDExZGMyOTMtMDgyYi00NGIwLWJhMTEtOTdkZGFjNmZiMTEwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_FMjpg_UX1000_.jpg",
      cover: "https://images.unsplash.com/photo-1542204165-65bf26472b9b?auto=format&fit=crop&q=80&w=2000",
      logo: "",
      rating: "9.0/10",
      votes: "110K+ Votes",
      ratingColor: "text-amber-400",
      tags: ['Action', 'Crime', 'Thriller'],
      imdb: "7.7",
      pg: "R",
      duration: "2h 49m",
      description: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances.",
      director: "Chad Stahelski",
      writers: "Shay Hatten • Michael Finch",
      stars: "Keanu Reeves • Laurence Fishburne"
    }
];

export const heroBackground = "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&q=80&w=2000";
